version: "3"
services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/react-app
      - ./src:/app/src
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
